title: CAMTREES Database
description: Everything volunteers and database admins need to know about the CAMTREES Database.
theme: just-the-docs

# Our GitHub Pages repository
url: https://camtrees.github.io

# We don't want any auxiliary links shown at the top right on all pages
# aux_links:
#   Template Repository: https://github.com/just-the-docs/just-the-docs-template

# Open external links in new tabs
nav_external_links_new_tab: true

# Colors defined for various callout enclosures
callouts:
  note:
    title: Note
    color: green
  caution:
    title: Caution
    color: yellow
  warning:
    title: Warning
    color: red

# Provide a Copy button in code blocks
enable_copy_code_button: true
